backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

  collections:
    - name: "dir1"
      label: "Dir1"
      folder: "content/dir1"
      create: true
      slug: "{{year}}-{{slug}}"
      fields:
        - {label: "Title", name: "title", widget: "string", required: true }
        - {label: "Date", name: "date", widget: "date", required: true }
        - {label: "Draft", name: "draft", widget: "boolean", required: true }